project:
  type: website

website:
  title: "BlueNote-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

output-dir: docs # Quarto가 렌더링한 결과물을 docs/ 폴더에 저장



