name: Render and Publish Quarto Website

on:
  push:
    branches: main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for R files
        id: check_r_files
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '\.qmd$'; then
            echo "::set-output name=r_files_changed::true"
          else
            echo "::set-output name=r_files_changed::false"
          fi
        shell: bash

      - name: Check for Python files
        id: check_py_files
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '\.qmd$'; then
            echo "::set-output name=py_files_changed::true"
          else
            echo "::set-output name=py_files_changed::false"
          fi
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v5
        if: steps.check_py_files.outputs.py_files_changed == 'true'
        with:
          python-version: '3.13' # GitHub Actions에서 3.13.x 최신 버전을 설치합니다.

      - name: Install Python dependencies
        if: steps.check_py_files.outputs.py_files_changed == 'true'
        run: |
          python -m pip install --upgrade pip # 현재 설정된 Python 환경의 pip를 업데이트
          # Quarto의 Python 코드 실행에 필수적인 Jupyter 관련 패키지들
          python -m pip install ipykernel pyyaml nbformat jupyter_client jupyter_core

          # 여러분의 코드에 필요한 기타 라이브러리들
          python -m pip install pandas scikit-learn numpy
          # 만약 추가적인 라이브러리가 있다면 여기에 python -m pip install [library_name] 형태로 추가하세요.

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        if: steps.check_r_files.outputs.r_files_changed == 'true'
        with:
          r-version: '4.x'

      - name: Install R dependencies
        if: steps.check_r_files.outputs.r_files_changed == 'true'
        run: |
          R -e 'install.packages(c("tidyverse", "caret", "tidymodels"))'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto project
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs